ruby-bench/ruby-bench-web

Gemfile, Gemfile.lock
```bundle``` commands shows up a warning message like the following.
```
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without
a block is a security risk, and may result in installing unexpected gems. To resolve this 
warning, use a block to indicate which gems should come from the secondary source. To upgrade
this warning to an error, run `bundle config disable_multisource true`.
```
PR solve this security fix, and disable warning message.
=> add source block to solve multiple primary source warning

app/assets/stylesheets/modules/_body.scss
On Chrome, initially it was:
I changed it to:
=> Disable webkit appearance for select element

app/views/static_pages/hardware.html.haml, app/views/static_pages/landing.html.haml
This is actually mostly a reversion of https://github.com/ruby-bench/ruby-bench-web/pull/88 -- not sure why that happened, but it's incorrect.  The benchmarks "are run", not "are ran".
=> Grammar fixes

app/assets/javascripts/initialize.js
Displaycount variable which stores Benchmark run display count value. Displaycount is set to undefined and also not used any where in the code.
=> remove unused Displaycount

app/models/commit.rb, test/models/commit_test.rb
URL validation is done through URI regex and necessary tests are also listed
=> add url validation to commit model

app/models/sponsors.rb, config/initializers/load_settings.rb, config/sponsors.yml, test/acceptance/sponsors_test.rb
This PR stores sponsors data in YAML file and loads file at application load time. Changes scope of sponsors method to private.
As initializer file is changed server need to be restarted to view updated changes.
=> Sponsor data access improvements

db/seeds.rb
I tend to start up projects using:
```
bundle exec rake db:create db:migrate db:seed db:schema:dump db:test:prepare
```
This fails since the `BenchmarkRun` model has been setup before the field `benchmark_type_id` was added to the schema:
```
ActiveRecord::UnknownAttributeError: unknown attribute 'benchmark_type_id' for BenchmarkRun.
```
before
-------
If I try to run `rake db:seed` again, it will blow complain about the records already existing.
after
-----
It lets me run `rake db:seed` again.
While this change does not make the `db:seeds` completely idempotent, it does allow it be be run again successfully and duplicates minimal data.
=> Make seeds.rb closer to idempotent

Gemfile, Gemfile.lock, test/acceptance/test_helper.rb, test/acceptance/view_benchmark_graphs_test.rb, test/test_helper.rb
This change fixes the issue of `view-benchmark-graph-test.rb` timing out:
- Add 'capybara-screenshot'
- Fix database_cleaner to reset the DB properly
- Fix timimg out of "User should be able to select number of benchmark runs to display for long running benchmark graphs"
=> Fix 'view-benchmark-graph-test.rb' timing out

db/seeds.rb
In development, running `bundle exec rake db:setup` with the current `db/seeds.rb` causes the following (a result from `ao_bench` is displayed in the graph for `ab_bench`):
The reverse (a result from `ab_bench` is displayed in the graph for `ao_bench`) is true as well.  
This PR resolves this problem, as follows:
If this is intended behaviour, then feel free to ignore this PR.
=> Possible typo in database seed benchmark name

app/assets/stylesheets/modules/_footer.scss
The footer links on each page were off-centre. This centres them again.
before:
after:
=> Fix footer links so that they're centered

.travis.yml
This fixes the travis build, which kept saying to upgrade to PhantomJS >= 2.1.1
Solution taken from [here](https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-200965782)
=> Install phantomJS 2.1.1 manually to fix travis

app/services/github_event_handler.rb, test/integration/github_event_handler_test.rb
@tgxworld I guess we only want to track push events on master/trunk branches, so we need to check if push occured to main branch.
Note: we didn't need this check on fork since we had events only on main branch.
=> Handle only commits to main branches

Gemfile, Gemfile.lock, app/services/commits_runner.rb, app/services/manual_runner.rb, config/secrets.yml, test/acceptance/sponsors_test.rb, test/services/commits_runner_test.rb, test/services/manual_runner_test.rb, test/test_helper.rb
I needed to run Sequel benchmarks for last 2000 commits. So far I could do it in production console in a pretty hacky (unsafe) way. Therefore I want to add `app/services/manual_runner.rb` which would fetch, store and run last 2000 commits from github api. That way we could run last number of commits manually in a tested way.
=> Add manual runner

app/assets/javascripts/modules/chart.js.erb, app/helpers/charts_helper.rb
Commit messages containing ruby like string interpolation syntax were causing problem with chart categories and tooltips.
On ruby side messages are being received escaped `\#{ ... }` which caused error in javascript on `JSON.parse`. So before drawing chart I removed those escapements.
I struggled a bit with this but got help https://stackoverflow.com/questions/44630300/why-jquery-cant-parse-inside-array-string/44630468#44630468
=> Fix commits chart data

.travis.yml
Adding deploy server address can't be added to ssh known hosts via travis addons, because it is being executed before exporting secret environment variables (which is needed to read `$DEPLOY_HOST`).
=> Disable StrictHostKeyChecking on ssh

Gemfile, Gemfile.lock, test/acceptance/sponsors_test.rb, test/acceptance/test_helper.rb
Acceptance tests were flaky for some time due to possible race conditions. 
I found out that Capybara shouldn't be used with integration test (`ActionDispatch::IntegrationTest`), therefore I replaced it with `Capybara::Rails::TestCase`.
http://blowmage.com/minitest-rails-capybara/
It looks like this recovered test suite - I've run it 10 times in for loop and no flaky error was raised.
=> Use minitest-rails-capybara for acceptance tests

app/services/commits_runner.rb, app/services/manual_runner.rb, test/services/manual_runner_test.rb
There was a bug when running less than 100 latest commits. It was because of paginating 100 commits per page.
Now it's possible to run only latest or last 20 or 50 commits.
=> Manually run only latest commit

Gemfile, Gemfile.lock, config/initializers/bugsnag.rb, config/initializers/sentry.rb
We benefit from Sentry Sponsored plan with unlimited members on projects.
I plan to set it up on ruby-bench-suite also to catch errors :tada:
=> Replace bugsnag with Sentry

.travis.yml, Gemfile, Gemfile.lock, test/models/benchmark_type_test.rb, test/test_helper.rb
`test/models/benchmark_type_test.rb:29` was failing because of different ordered arrays. Added custom Minitest assertion for array matching.
=> Fix flaky test

app/controllers/benchmark_runs_controller.rb, app/controllers/repos_controller.rb
When new run is being saved for certain benchmark, we want to invalidate cache for both comparison charts.
For example -- when new run for `pg/scope_all` is received, we want to invalidate cache for both charts:
https://rubybench.org/ged/ruby-pg/commits?result_type=pg/scope_all&display_count=2000&compare_with=activerecord/postgres_scope_all
and
https://rubybench.org/rails/rails/commits?result_type=activerecord/postgres_scope_all&display_count=2000&compare_with=pg/scope_all
=> Fix redis cache deletion

app/services/chart_builder.rb, test/services/chart_builder_test.rb
When using "Show the last 2000 Results", the JIT graph appears only in the commits which didn't have JIT.
https://rubybench.org/ruby/ruby/commits?result_type=app_erb&display_count=2000
Fill `nil` for the commits which don't have `*_jit` result in the chart.
=> Fix chart builder logic for JIT

Gemfile.lock
As I'm using Ubuntu 18.04 which has OpenSSL 1.1.0, puma 3.6.0 couldn't be installed. So I want to upgrade puma's version to pass `bundle install`.
=> bundle update puma

app/controllers/repos_controller.rb, app/models/benchmark_run.rb, test/models/benchmark_run_test.rb
The problem here is that if you have 2 `benchmark_type` with the same `category` value (let's say "discourse_home") but different `repo_id`, you'd get results from both repos when viewing benchmark results for one of them only. I noticed this bug while I was making discourse benchmark run on rails releases which we already run on ruby commits.
=> Release benchmarks should also filter by repo_id so we don't get mixed results

app/assets/javascripts/application/initialize.js, app/assets/stylesheets/modules/_user-scripts.scss, app/controllers/benchmark_runs_controller.rb, app/controllers/repos_controller.rb, app/controllers/session_controller.rb, app/controllers/user_scripts_controller.rb, app/jobs/remote_server_job.rb, app/jobs/run_user_bench.rb, app/services/commits_runner.rb, app/services/user_bench.rb, app/views/repos/_form.html.haml, app/views/user_scripts/index.html.haml, config/locales/en.yml, config/routes.rb, db/migrate/20190702200657_add_from_user_to_benchmark_types.rb, db/schema.rb, test/controllers/user_scripts_controller_test.rb, test/jobs/remote_server_job_test.rb, test/jobs/run_user_bench_test.rb, test/services/user_bench_test.rb, test/test_helper.rb
This will allow certain users that are verified via [community.rubybench.org](https://community.rubybench.org) to run their own ruby benchmarks against one or a range of ruby commits. Results will gradually appear at https://rubybench.org/ruby/ruby/commits.
Screenshot:
=>  Feature: Allow users to run their own Ruby benchmarks
