ruby-bench/ruby-bench-web

app/views/repos/_show_chart.html.haml, app/views/repos/show.js.erb
Fixes: https://github.com/ruby-bench/ruby-bench-web/issues/6.
=> Fix bug where charts are not able to zoom.

app/assets/javascripts/modules/chart.js.erb, app/assets/javascripts/modules/release_chart.js.erb
Closes https://github.com/ruby-bench/ruby-bench-web/issues/14.
=> Fix overlapping legends.

app/assets/javascripts/modules/chart.js.erb, app/controllers/repos_controller.rb, app/views/repos/_show_chart.html.haml, app/views/repos/show.html.haml, app/views/repos/show.js.erb, test/acceptance/view_benchmark_graphs_test.rb, test/fixtures/benchmark_runs.yml, test/models/benchmark_run_test.rb
=> Display memory benchmarks graph.

.travis.yml
Closes: https://github.com/ruby-bench/ruby-bench-web/issues/30.
=> Fix failing selenium tests on TravisCI.

README.md
=> fix typo on testing portion of README.md

app/assets/javascripts/modules/chart.js.erb
Fixes: https://github.com/ruby-bench/ruby-bench-web/issues/40.
=> Fix click on commit feature.

app/views/layouts/_footer.html.haml
Added **@yangshun** into the footer :joy:
=> Include designer into footer

app/assets/stylesheets/modules/_hardware.scss, app/views/static_pages/hardware.html.haml
Will add in more design fluff in future. Currently just a change in skin from the previous version.
=> Hardware Page Revamp

app/assets/stylesheets/modules/_navbar.scss, app/views/layouts/_top_nav.html.haml
=> Rename top nav

app/assets/stylesheets/modules/_footer.scss, app/views/layouts/_footer.html.haml
Hide sponsors and put navlinks in footer too. Navlinks should be extracted out into an object since they are repeated in nav and footer.
=> New footer

app/views/layouts/application.html.haml
=> Fix typo in meta tag

app/views/static_pages/hardware.html.haml, app/views/static_pages/landing.html.haml
Fixed little grammatical errors to make it flow a little better ☺️
=> Fixed minor grammar errors

db/seeds.rb
=> Fix outdated db seed data which was not reflecting updated schema

README.md
So people can click to check your build.
[Updated README.md](https://github.com/JuanitoFatas/ruby-bench-web/blob/48ce259/README.md).
=> Make travis badge link to travis-ci.org [ci skip]

app/controllers/repos_controller.rb
One more minor fix removed params which already calculated :smile: I like this project
=> remove params again

app/views/repos/_form.html.haml
- Navigate benchmark types
- Addresses #78
=> Add left and right arrow keys

app/jobs/remote_server_job.rb, test/jobs/remote_server_job_test.rb
Run liquid benchmarks with ruby benchmarks using an option
=> Add option to run liquid benchmarks

app/jobs/remote_server_job.rb, app/services/benchmark_pool.rb, app/services/github_event_handler.rb, test/integration/github_event_handler_test.rb, test/jobs/remote_server_job_test.rb, test/services/benchmark_pool_test.rb
=> Add sequel benchmarks

app/services/github_event_handler.rb
Jeremy configured webhook on sequel official repo :tada:
=> Sequel events are comming from Jeremy's repo

app/views/repos/_commits_chart.html.haml, app/views/repos/_script.html.haml, app/views/repos/commits.html.haml, app/views/repos/commits.js.erb, test/acceptance/compare_benchmarks_test.rb
We need to see both benchmark scripts when comparing :chart_with_downwards_trend:
=> Show both scripts below comparing commits graphs

.travis.yml
https://travis-ci.org/ruby-bench/ruby-bench-web/builds/247016019#L629
=> Fix automatic deploy - protect private key

.travis.yml
- Fix automatic deploy on production branch: protect private key with `chmod 600`
=> Deploy last changes

app/jobs/remote_server_job.rb, app/services/benchmark_pool.rb, test/jobs/remote_server_job_test.rb, test/services/benchmark_pool_test.rb
https://github.com/ruby-bench/ruby-bench-web/issues/242  :hammer_and_wrench:
=> Add ssh method to support PG suite

app/controllers/benchmark_runs_controller.rb
=> Remove double assignment to initiator

lib/tasks/temporary/ruby-pg.rake
Once this is deployed I will run it to have ruby-pg repo in production.
At first I am going to run commits through manual runner. If needed, we can later on setup webhook to automatically trigger run.
=> Add temporary rake task

app/jobs/remote_server_job.rb, test/jobs/remote_server_job_test.rb
This commit https://github.com/ruby-bench/ruby-bench-docker/commit/43e980360435d5f31ef1dc7631fc0398e15a45a7 has changed how discourse benchmarks are run which means we need to update how the benchmarks are invoked from here.
=> Discourse bench fix
